image_root: '/GPFS/rhome/kejinli/workspace/multi-modal/BLIP/BLIP4caption/caption_data/coco/'
ann_root: '/GPFS/rhome/kejinli/workspace/multi-modal/BLIP/BLIP4caption/caption_data/coco/annotations'
coco_gt_root: '/GPFS/rhome/kejinli/workspace/multi-modal/BLIP/BLIP4caption/caption_data/coco/annotations'

# set pretrained as a file path or an url
pretrained: '/GPFS/rhome/kejinli/workspace/multi-modal/BLIP/BLIP4caption/pretrained_model/model_base_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 28
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 20  
min_length: 5
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 5

